import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header.js";
import SideBar from "./components/sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <div className="flex w-full">
        <div className="w-[150px]">
        <SideBar />
        </div>
        <div className="w-full flex flex-col">
        <Header />
        {children}
        </div>
        </div>
      </body>
    </html>
  );
}
